# .streamlit/config.toml dosyasının yeni içeriği

[theme]
# Ana etkileşim rengi (Butonlar, seçili öğeler vb.)
primaryColor = "#FDB022"  # Gold (accent)

# Ana arka plan (CSS ile degrade ekleyeceğimiz için bu bir temel renk olacak)
backgroundColor = "#0E1628" # Yüzey Alt

# Yan menü ve diğer ikincil arka planlar
secondaryBackgroundColor = "#111A33" # Yüzey (card bg)

# Ana metin rengi
textColor = "#E6EAF5" # Metin (primary)

# Yazı tipi
font = "sans serif"
